version: "3"
services:
  nexus:
    image: sonatype/nexus3
    volumes:
      - ./docker-data/nexus-data:/nexus-data
    ports:
      - 8081:8081
    container_name: nexus
    restart: unless-stopped
  
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./docker-data/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/lib/jvm/java-8-openjdk-amd64:/opt/openjdk
      # - ./docker-data/jenkins-docker-certs:/certs/client:ro
    restart: unless-stopped