version: "3"
services:
  nexus:
    image: sonatype/nexus3
    volumes:
      - ./docker-data/nexus-data:/nexus-data
    ports:
      - 8081:8081
    container_name: nexus
    restart: unless-stopped
